-- SQL schema for BTL_SPMeVaBe (MariaDB)

CREATE TABLE IF NOT EXISTS SanPham (
  MaSanPham INT AUTO_INCREMENT PRIMARY KEY,
  TenSanPham VARCHAR(255) NOT NULL,
  ThongTinSanPham TEXT,
  GiaTien DECIMAL(10,2) DEFAULT 0,
  SoLuong INT DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS KhachHang (
  id INT AUTO_INCREMENT PRIMARY KEY,
  HoTen VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  DienThoai VARCHAR(50),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  Status VARCHAR(50) DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS AnhSanPham (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_MaSanPham INT NOT NULL,
  url VARCHAR(1024) NOT NULL,
  altText VARCHAR(255),
  sortOrder INT DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_MaSanPham) REFERENCES SanPham(MaSanPham) ON DELETE CASCADE
);
